### ISSUE TITLE
Deprecated keys are registered to root, therefore child nodes cannot be used independently

### ISSUE THREAD

**Issue by Rizhiy** [rbgirshick/yacs#14]
I would like to use child nodes of main config independently from root node, but because deprecated keys are registered to root node that is not entirely possible.

**Comment by rbgirshick** [comment]
@Rizhiy can you provide a code snippet showing what you'd like to do? I want to make sure I fully understand the usage case. Thanks!

**Comment by Rizhiy** [comment]
Let's say I have the following config:

```python
from yacs.config import CfgNode as CN

root = CN()
root.A = CN()
root.A.B = 1
```

Which I sometimes load as a whole:
```python
root.merge_from_file('root.yaml')
```

And sometimes in several steps/from several files in different parts of code:
```python
A_cfg = root.A
A_cfg.merge_from_file('A.yaml')
```

If I register a deprecated key in root:
```python
root.register_deprecated_key('A.C')
```

I won't be able to load `A_cfg` separately as deprecated key is registered in `root`.

**Comment by Rizhiy** [comment]
If I register deprecated key in the child node:
```python
root.A.register_deprecated_key('C')
```
It will complain when I try to load the config as a whole.

**Comment by Rizhiy** [comment]
@rbgirshick Hi, I'm working on potential fix to this issue and have a few questions. What is the expected behaviour in the following cases, as it is not clear from code/tests:
* Existing key is registered as deprecated, i.e.:
```python
cfg = CN()
cfg.A = 1
cfg.register_deprecated_key('A')
```
* Existing key is registered as deprecated, but later accessed:
```python
cfg = CN()
cfg.A = 1
cfg.register_deprecated_key('A')
a = cfg.A
```
* Other way around, deprecated key is assigned a value:
```python
cfg = CN()
cfg.register_deprecated_key('A')
cfg.A = 1
```
https://github.com/rbgirshick/yacs/blob/a9297698ae3035b0036f87f0b327283e62f54e6a/yacs/tests.py#L206

Same questions regarding `renamed` keys.

**Comment by Rizhiy** [comment]
I think it would be better to move handling of deprecated/renamed keys to `CfgNode.__set/getattr__` and don't allow any access to deprecated/renamed keys.

**Comment by Rizhiy** [comment]
I have looked at the current code and it will take quite a lot of work to get the effect that I want and it might break some existing functionality.
Therefore I'm closing the issue for now.
