### ISSUE TITLE
[QUESTION] Tuple overload

### ISSUE THREAD

**Issue by miguelvr** [rbgirshick/yacs#21]
How can I overload a tuple config parameter from the command line?

Thanks

**Comment by rbgirshick** [comment]
If properly quoted, it should work. E.g. for a tuple of strings:

`python your_script.py FOO.BAR "('x', 'y', 'z',)"`

If the tuple is a singleton, make sure to include a trailing comma:

`python your_script.py FOO.BAR "('x',)"`

Tuple of numbers:

`python your_script.py FOO.BAR "(1, 2, 3.14159, )"`

And so on...
