### ISSUE TITLE
Key "ON" interpreted as True?

### ISSUE THREAD

**Issue by ruiyuanlu** [rbgirshick/yacs#48]
Hi, I have a yaml file that use `ON` as key name, but it will be interpreted as `True`

For example:
```yaml
SOME_FEATURE:
  ON: False
```
will be loaded as {SOME_FEATURE: {True: False}} and cause type error.

This might be a bug of ConfigNode.load_cfg method?

**Comment by rbgirshick** [comment]
This is just a basic property of yaml:

```python
import yaml
d = yaml.load("ON: foo")
print(d)
```
Out:
```
{True: 'foo'}
```
