### ISSUE TITLE
how to overide command-line args?

### ISSUE THREAD

**Issue by seoha-kim** [rbgirshick/yacs#50]
i usually use yacs with config file as below:
python3 run.py --cfg /home/plask/seoha/kubeflow/metrabs/configs/aist_only_hrnet_new_aug_all.yaml

eg.
TRAIN:
  AUGMENT : true
  OPTIM: "ranger"
  LR: 0.0001
  BACKBONE_TRAIN: true
  BATCH_SIZE : 16
  OCCLUDE_AUGMENT : false
  NUM_STEPS_START_ABS : 10000000

but i wand to override some args like

python3 run.py --cfg /home/plask/seoha/kubeflow/metrabs/configs/aist_only_hrnet_new_aug_all.yaml --train-optim "adam" --train-lr 1e-4 

i have to override with command-line(not modifying yaml file)
how can i do this?

**Comment by XinyiXuXD** [comment]
Hi, I have the same request as U. Have U solved this issue？
