### ISSUE TITLE
Git tags for releases

### ISSUE THREAD

**Issue by kwohlfahrt** [rbgirshick/yacs#7]
Would it be possible to add git tags for releases?

I'm looking to package this for [Nix](https://nixos.org/), and would like to be able to run the tests on the fetched source during the build. The PyPI source tarball does not include the required examples directory, so a git tag would be nice.

**Comment by rbgirshick** [comment]
Sorry it took me a long time to do this. I'll start making tagged releases going forward (and have backfilled v0.1.4 and v0.1.5).
