### ISSUE TITLE
[Feature request] Allow CfgNode to have keys added from yaml files

### ISSUE THREAD

**Issue by Rizhiy** [rbgirshick/yacs#8]
In my experiments I sometimes need to use a function with many keyword arguments.
Listing all possible kwargs in main config is impractical, since I can't easily determine default values and sometimes there are too many of them.

It would be nice to be able to create `CfgNode` that allows addition of new attributes from yaml file.

**Comment by Rizhiy** [comment]
Created a pull request: #9

**Comment by rbgirshick** [comment]
Merged from #9.
